### ISSUE TITLE
Attempting to map constant scalar values leads to `CannotResolveTypeFromUnion` rather than `MappingError`

### ISSUE THREAD

**Issue by Ocramius** [CuyZ/Valinor#28]
Taking following example:

```php
<?php

namespace My\App;

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\MapperBuilder;

require_once __DIR__ . '/Valinor/vendor/autoload.php';

class Role
{
    /** @var 'admin'|'user' */
    public string $name;
}


$mapper = (new MapperBuilder())
    ->mapper();

try {
    $r = $mapper
        ->map(
            Role::class,
            [
                'name' => 'wrong'
            ]
        );

    var_dump($r);
} catch (MappingError $e) {
    var_dump(array_map(
        static fn (array $exceptions) => array_map(static fn (\Throwable $e) : array => [
            $e->getMessage(),
            get_class($e),
        ], $exceptions),
        $e->describe()
    ));
}
```

The expectation is that the `MappingError` is rendered (as per `catch` block). The current implementation throws a much deeper exception though:

```
 php example-error-handling.php 

Fatal error: Uncaught CuyZ\Valinor\Type\Resolver\Exception\CannotResolveTypeFromUnion: Impossible to resolve the type from the union `admin|user` with a value of type `string`. in /app/Valinor/src/Type/Resolver/Union/UnionScalarNarrower.php:40
Stack trace:
#0 /app/Valinor/src/Type/Resolver/Union/UnionNullNarrower.php(41): CuyZ\Valinor\Type\Resolver\Union\UnionScalarNarrower->narrow(Object(CuyZ\Valinor\Type\Types\UnionType), 'wrong')
#1 /app/Valinor/src/Mapper/Tree/Visitor/UnionShellVisitor.php(29): CuyZ\Valinor\Type\Resolver\Union\UnionNullNarrower->narrow(Object(CuyZ\Valinor\Type\Types\UnionType), 'wrong')
#2 /app/Valinor/src/Mapper/Tree/Visitor/AggregateShellVisitor.php(22): CuyZ\Valinor\Mapper\Tree\Visitor\UnionShellVisitor->visit(Object(CuyZ\Valinor\Mapper\Tree\Shell))
#3 /app/Valinor/src/Mapper/Tree/Builder/ShellVisitorNodeBuilder.php(27): CuyZ\Valinor\Mapper\Tree\Visitor\AggregateShellVisitor->visit(Object(CuyZ\Valinor\Mapper\Tree\Shell))
#4 /app/Valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(23): CuyZ\Valinor\Mapper\Tree\Builder\ShellVisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#5 /app/Valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(21): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#6 /app/Valinor/src/Mapper/Tree/Builder/ClassNodeBuilder.php(43): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell))
#7 /app/Valinor/src/Mapper/Tree/Builder/CasterNodeBuilder.php(35): CuyZ\Valinor\Mapper\Tree\Builder\ClassNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#8 /app/Valinor/src/Mapper/Tree/Builder/VisitorNodeBuilder.php(28): CuyZ\Valinor\Mapper\Tree\Builder\CasterNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#9 /app/Valinor/src/Mapper/Tree/Builder/ValueAlteringNodeBuilder.php(31): CuyZ\Valinor\Mapper\Tree\Builder\VisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#10 /app/Valinor/src/Mapper/Tree/Builder/ShellVisitorNodeBuilder.php(30): CuyZ\Valinor\Mapper\Tree\Builder\ValueAlteringNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#11 /app/Valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(23): CuyZ\Valinor\Mapper\Tree\Builder\ShellVisitorNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#12 /app/Valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(21): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder))
#13 /app/Valinor/src/Mapper/TreeMapperContainer.php(57): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell))
#14 /app/Valinor/src/Mapper/TreeMapperContainer.php(31): CuyZ\Valinor\Mapper\TreeMapperContainer->node('My\\App\\Role', Array)
#15 /app/example-error-handling.php(25): CuyZ\Valinor\Mapper\TreeMapperContainer->map('My\\App\\Role', Array)
#16 {main}
  thrown in /app/Valinor/src/Type/Resolver/Union/UnionScalarNarrower.php on line 40
```

**Comment by romm** [comment]
Indeed, this should be caught in the `MappingError`. If you implement the interface `\CuyZ\Valinor\Mapper\Tree\Message\Message` in the class `\CuyZ\Valinor\Type\Resolver\Exception\CannotResolveTypeFromUnion` that should solve it. But the message is maybe not the best one though, maybe we should change it? WDYT?

**Comment by Ocramius** [comment]
I'll see if I can send a patch for this, but unlikely this week :D

**Comment by romm** [comment]
Fixed by e834cdc5

**Comment by Ocramius** [comment]
Thanks @romm!

**Comment by romm** [comment]
You're welcome, now go and enjoy the last release! 😛

**Comment by Ocramius** [comment]
I wish: currently delegated other devs to do that for me xD
