### ISSUE TITLE
Enum not allowed as registered constructor return type

### ISSUE THREAD

**Issue by arnaud-lb** [CuyZ/Valinor#316]
Valinor refuses registered constructors whose return type is an enum.

The following mapper fails with the error `Invalid return type Foo for constructor Foo::from(), it must be a valid class name` when `Foo` is an enum:

``` php
$value = (new MapperBuilder())
    ->registerConstructor(Foo::from(...))
    ->mapper()
    ->map(C::class, $source);
```

Full reproducer: https://gist.github.com/arnaud-lb/748fa5f38437b2a0c32850adc88158e3

Backtrace:

```
PHP Fatal error:  Uncaught CuyZ\Valinor\Mapper\Object\Exception\InvalidConstructorReturnType: Invalid return type `Foo` for constructor `Foo::from()`, it must be a valid class name. in /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php:97
Stack trace:
#0 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php(65): CuyZ\Valinor\Mapper\Object\Factory\ConstructorObjectBuilderFactory->constructorMatches()
#1 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php(40): CuyZ\Valinor\Mapper\Object\Factory\ConstructorObjectBuilderFactory->builders()
#2 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/DateTimeZoneObjectBuilderFactory.php(36): CuyZ\Valinor\Mapper\Object\Factory\ConstructorObjectBuilderFactory->for()
#3 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/DateTimeObjectBuilderFactory.php(34): CuyZ\Valinor\Mapper\Object\Factory\DateTimeZoneObjectBuilderFactory->for()
#4 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/CollisionObjectBuilderFactory.php(24): CuyZ\Valinor\Mapper\Object\Factory\DateTimeObjectBuilderFactory->for()
#5 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/StrictTypesObjectBuilderFactory.php(21): CuyZ\Valinor\Mapper\Object\Factory\CollisionObjectBuilderFactory->for()
#6 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/CacheObjectBuilderFactory.php(31): CuyZ\Valinor\Mapper\Object\Factory\StrictTypesObjectBuilderFactory->for()
#7 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/ProxyClassNodeBuilder.php(38): CuyZ\Valinor\Mapper\Object\Factory\CacheObjectBuilderFactory->for()
#8 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/CasterNodeBuilder.php(25): CuyZ\Valinor\Mapper\Tree\Builder\ProxyClassNodeBuilder->build()
#9 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/UnionNodeBuilder.php(39): CuyZ\Valinor\Mapper\Tree\Builder\CasterNodeBuilder->build()
#10 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/InterfaceNodeBuilder.php(52): CuyZ\Valinor\Mapper\Tree\Builder\UnionNodeBuilder->build()
#11 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php(26): CuyZ\Valinor\Mapper\Tree\Builder\InterfaceNodeBuilder->build()
#12 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/IterableNodeBuilder.php(28): CuyZ\Valinor\Mapper\Tree\Builder\CasterProxyNodeBuilder->build()
#13 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/StrictNodeBuilder.php(37): CuyZ\Valinor\Mapper\Tree\Builder\IterableNodeBuilder->build()
#14 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(33): CuyZ\Valinor\Mapper\Tree\Builder\StrictNodeBuilder->build()
#15 /tmp/bug/vendor/cuyz/valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(18): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build()
#16 /tmp/bug/vendor/cuyz/valinor/src/Mapper/TypeTreeMapper.php(45): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build()
#17 /tmp/bug/vendor/cuyz/valinor/src/Mapper/TypeTreeMapper.php(26): CuyZ\Valinor\Mapper\TypeTreeMapper->node()
#18 /tmp/bug/bug.php(31): CuyZ\Valinor\Mapper\TypeTreeMapper->map()
#19 {main}
  thrown in /tmp/bug/vendor/cuyz/valinor/src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php on line 97
```

`$returnType` is a `NativeEnumType` in https://github.com/CuyZ/Valinor/blob/1577233ac9dce444af61bb482f5a744e38eaf739/src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php#L96-L97

**Comment by romm** [comment]
Hi @arnaud-lb, version 1.3.0 [has been released](https://github.com/CuyZ/Valinor/releases/tag/1.3.0), with a support for enum constructors. Enjoy!

**Comment by arnaud-lb** [comment]
Thank you!
