### ISSUE TITLE
Mixing phpstan-type and psalm-type phpdocs breaks type resolution

### ISSUE THREAD

**Issue by danog** [CuyZ/Valinor#428]
Example:

```php
<?php

require 'vendor/autoload.php';

/**
 * @psalm-type AliasShapedArray = array{foo: string, bar: int}
 * @phpstan-type AliasShapedArrayNested = array{baz: AliasShapedArray}
 */
class a {
    /** 
     * @param AliasShapedArrayNested $a  
     */
    public function __construct(
        public readonly array $a,
        public readonly int $b = 0
    )
    {
        
    }
}

$res = (new \CuyZ\Valinor\MapperBuilder())
    ->allowSuperfluousKeys()
    ->mapper()
    ->map(
        'a',
        [
            'a' => ['baz' => ['foo' => 'test', 'bar' => 123]],
        ]
    );
var_dump($res);
```

Result:
```
PHP Fatal error:  Uncaught AssertionError: assert(!$type instanceof UnresolvableType) in /home/daniil/repos/valinor/src/Mapper/Tree/Shell.php:31
Stack trace:
#0 /home/daniil/repos/valinor/src/Mapper/Tree/Shell.php(31): assert()
#1 /home/daniil/repos/valinor/src/Mapper/Tree/Shell.php(41): CuyZ\Valinor\Mapper\Tree\Shell->__construct()
#2 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/ObjectNodeBuilder.php(50): CuyZ\Valinor\Mapper\Tree\Shell->child()
#3 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/ObjectNodeBuilder.php(23): CuyZ\Valinor\Mapper\Tree\Builder\ObjectNodeBuilder->children()
#4 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/NativeClassNodeBuilder.php(39): CuyZ\Valinor\Mapper\Tree\Builder\ObjectNodeBuilder->build()
#5 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/CasterNodeBuilder.php(24): CuyZ\Valinor\Mapper\Tree\Builder\NativeClassNodeBuilder->build()
#6 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/UnionNodeBuilder.php(37): CuyZ\Valinor\Mapper\Tree\Builder\CasterNodeBuilder->build()
#7 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/InterfaceNodeBuilder.php(51): CuyZ\Valinor\Mapper\Tree\Builder\UnionNodeBuilder->build()
#8 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php(24): CuyZ\Valinor\Mapper\Tree\Builder\InterfaceNodeBuilder->build()
#9 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/IterableNodeBuilder.php(26): CuyZ\Valinor\Mapper\Tree\Builder\CasterProxyNodeBuilder->build()
#10 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/StrictNodeBuilder.php(36): CuyZ\Valinor\Mapper\Tree\Builder\IterableNodeBuilder->build()
#11 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(33): CuyZ\Valinor\Mapper\Tree\Builder\StrictNodeBuilder->build()
#12 /home/daniil/repos/valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(16): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build()
#13 /home/daniil/repos/valinor/src/Mapper/TypeTreeMapper.php(44): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build()
#14 /home/daniil/repos/valinor/src/Mapper/TypeTreeMapper.php(25): CuyZ\Valinor\Mapper\TypeTreeMapper->node()
#15 /home/daniil/repos/valinor/a.php(25): CuyZ\Valinor\Mapper\TypeTreeMapper->map()
#16 {main}
  thrown in /home/daniil/repos/valinor/src/Mapper/Tree/Shell.php on line 31
```

**Comment by romm** [comment]
Should be fixed by #521, thanks for the report!
