### ISSUE TITLE
Valinor may crash when encountering a PHPStan/Psalm type syntax it doesn't support yet

### ISSUE THREAD

**Issue by arnaud-lb** [CuyZ/Valinor#448]
It appears that Valinor may crash when encountering a type syntax it doesn't support yet. This can be an issue as this prevents from using some PHPStan/Psalm features on objects that may be mapped by Valinor.

For example, the following code:
``` php
<?php

require 'vendor/autoload.php';

class B {}

class A
{
    /**
     * @phpstan-param ($a is 1 ? B : null) $b
     * @param B|null $b
     */
    public function __construct(
        public readonly int $a,
        public readonly ?B $b,
    ) {
    }
}

return (new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(
        A::class,
        new \CuyZ\Valinor\Mapper\Source\JsonSource('{"a":0,"b":null}')
    );
```

leads to this assertion failure:

```
PHP Fatal error:  Uncaught AssertionError: assert(!$type instanceof UnresolvableType) in src/Mapper/Tree/Shell.php:31
Stack trace:
#0 src/Mapper/Tree/Shell.php(31): assert()
#1 src/Mapper/Tree/Shell.php(41): CuyZ\Valinor\Mapper\Tree\Shell->__construct()
#2 src/Mapper/Tree/Builder/ObjectNodeBuilder.php(50): CuyZ\Valinor\Mapper\Tree\Shell->child()
#3 src/Mapper/Tree/Builder/ObjectNodeBuilder.php(23): CuyZ\Valinor\Mapper\Tree\Builder\ObjectNodeBuilder->children()
#4 src/Mapper/Tree/Builder/NativeClassNodeBuilder.php(39): CuyZ\Valinor\Mapper\Tree\Builder\ObjectNodeBuilder->build()
#5 src/Mapper/Tree/Builder/CasterNodeBuilder.php(24): CuyZ\Valinor\Mapper\Tree\Builder\NativeClassNodeBuilder->build()
#6 src/Mapper/Tree/Builder/UnionNodeBuilder.php(37): CuyZ\Valinor\Mapper\Tree\Builder\CasterNodeBuilder->build()
#7 src/Mapper/Tree/Builder/InterfaceNodeBuilder.php(51): CuyZ\Valinor\Mapper\Tree\Builder\UnionNodeBuilder->build()
#8 src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php(24): CuyZ\Valinor\Mapper\Tree\Builder\InterfaceNodeBuilder->build()
#9 src/Mapper/Tree/Builder/IterableNodeBuilder.php(26): CuyZ\Valinor\Mapper\Tree\Builder\CasterProxyNodeBuilder->build()
#10 src/Mapper/Tree/Builder/StrictNodeBuilder.php(36): CuyZ\Valinor\Mapper\Tree\Builder\IterableNodeBuilder->build()
#11 src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(33): CuyZ\Valinor\Mapper\Tree\Builder\StrictNodeBuilder->build()
#12 src/Mapper/Tree/Builder/RootNodeBuilder.php(16): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build()
#13 src/Mapper/TypeTreeMapper.php(44): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build()
#14 src/Mapper/TypeTreeMapper.php(25): CuyZ\Valinor\Mapper\TypeTreeMapper->node()
#15 test.php(24): CuyZ\Valinor\Mapper\TypeTreeMapper->map()
#16 {main}
  thrown in src/Mapper/Tree/Shell.php on line 31
```

Should Valinor fallback to the unprefixed `@param` in this case?

**Comment by romm** [comment]
Hey there, thanks for the report!

I think that the fallback option is not the best as it cannot be guaranteed that the `@param` annotation works as well.

I was thinking about adding a `@valinor-*` annotation support that has precedence over all the others, for the following cases: `@valinor-var`, `@valinor-param`, `@valinor-return`, `@valinor-extends`, `@valinor-template`, `@valinor-type`.

WDYT?

**Comment by romm** [comment]
@stiflerbox your usecase was actually a "bug" (rather an unwanted feature actually 😛 ), see #520.

**Comment by romm** [comment]
Better late than never 😅

Will be fixed in upcoming release via #830!
