### ISSUE TITLE
How to map generic types?

### ISSUE THREAD

**Issue by Ocramius** [CuyZ/Valinor#8]
To try out things, I attempted mapping a generic class, where the generic type parameter has not been provided:

```php
<?php

namespace My\App;

use CuyZ\Valinor\Attribute\StaticMethodConstructor;
use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\MapperBuilder;

require_once __DIR__ . '/Valinor/vendor/autoload.php';

/** @template T of mixed */
class MyGenericWrapper
{
    /** @var T */
    public mixed $value;
}

$mapper = (new MapperBuilder())
    ->withCacheDir(__DIR__ . '/cache')
    ->mapper();

var_dump($mapper->map(MyGenericWrapper::class, ['value' => 'who knows?']));
```

This leads to a clear exception:

```
php example.php 

Fatal error: Uncaught CuyZ\Valinor\Mapper\Exception\InvalidMappingTypeSignature: Could not parse the type `My\App\MyGenericWrapper` that should be mapped: No generic was assigned to the template(s) `T` for the class `My\App\MyGenericWrapper`. in /app/Valinor/src/Mapper/TreeMapperContainer.php:48
Stack trace:
#0 /app/Valinor/src/Mapper/TreeMapperContainer.php(31): CuyZ\Valinor\Mapper\TreeMapperContainer->node('My\\App\\MyGeneri...', Array)
#1 /app/example.php(23): CuyZ\Valinor\Mapper\TreeMapperContainer->map('My\\App\\MyGeneri...', Array)
#2 {main}
  thrown in /app/Valinor/src/Mapper/TreeMapperContainer.php on line 48
```

The `README.md` example is clear about generic types where the type parameter has been set: 

https://github.com/CuyZ/Valinor/blob/396f64a5246ccfe3f6f6d3211bac7f542a9c7fc6/README.md#L258-L259

How would one request a `MyGenericWrapper<int>` from the mapper, as a root de-serialization target?

**Comment by romm** [comment]
Hi @Ocramius, unfortunately type inferring for generics is not handled at all for now, I have to think about it, maybe it could be handled someday.

In the meantime, the following should work:

```php
$mapper->map(MyGenericWrapper::class . '<string>', ['value' => 'who knows?'])
```

Also, documentation is not finished at all on this topic, but note that you can use the following annotations:

```php
/**
 * @template T of mixed 
 * …or…
 * @template T // mixed is the default type
 *
 * You can also use advanced types:
 * @template T of int|float
 * @template T of SomeClass&SomeOtherClass
 * @template T of string|SomeClass
 * etc…
 */
class MyGenericWrapper
{
    /** @var T */
    public mixed $value;
}
```

**Comment by Ocramius** [comment]
Thanks for clarifying!
